var start = Date.now()
require('./operators.test.js')
require('./brackets.test.js')
require('./changes.test.js')
require('./helper.test.js')
require('./lookup.test.js')
require('./types.test.js')
require('./split.test.js')
require('./list.test.js')
console.error(Date.now() - start)
